import { ViewLayout } from './ViewLayout';
import { Widget, WidgetContext } from './Widget'
import { WidgetMessage } from './WidgetMessage';
import { ILayoutPresenter } from './ILayoutPresenter';
import { PageShell as PageShell } from './PageShell';
import { INotifiable } from './INotifiable';
import { UITemplateView } from './controls/UITemplateView';
import { AppStorage } from './AppStorage';
import { UIDialog } from './controls/UIDialog';
import { ModalAction } from './controls/ModalAction';
import { UIDialogBS5 } from './controls/UIDialogBS5';
import { VirtualFunction } from './VirtualFunction';
import { Misc } from './Misc';
import { UIPage } from './UIPage';

/**
 * A UIView represents an interface view set of user controls.
 * UIView's are loaded and unloaded all the time and they 
 * house a set of Widgets that give meaning to the view in 
 * front of the user. 
 * * We can say in general terms that 
 * "this is a 'screen' of the application"
 */
export abstract class UIView implements INotifiable
{
    /**
     * You must return a `ViewLayout` class instance to 
     * define the layout demarcations for this View
     * * See:
     * ```
     * class ViewLayout
     * ```
     */
    abstract buildLayout(): ViewLayout;

    /**
     * You must attach your Widgets variables with the divs 
     * contained in the Layout. 
     * Inside here, call the function `UIView.addWidgets(string, array)`
     * * You **MUST NOT** manipulate the Widgets here (access attributes and functions directly), because they don't exist yet
     * * Example:
     * ```
     * composeView(): void {
     * this.addWidgets('form-div-id', this.txtName, this.txtMail);
     * this.addWidgets('actionbar-div-id', this.btnSend, this.btnClear);
     * }
     * ``` 
     * */
    abstract composeView(): void;

    /**
     * When the entire View has been rendered, 
     * you can manipulate the Widgets properties, attributes, styles 
     * and other features here.
     * * You can retrieve and modify properties of divs generated by `ViewLayout` (`Row` and `Col`)
     * * You can also change Widget styles through 
     * standard Widget superclass functions
     * * Can load data into Widgets and do all necessary 
     * logical manipulation in your UIView from now on
     * * [EXAMPLE]
     * ```
onViewDidLoad(): void
{
    //get and style a div (by id) defined in ViewLayout
    var nav = this.shellPage.elementById('nav') as HTMLDivElement;
    nav.style.background = '#007bff';
    //apply batch css to a UIHead
    this.title.applyAllCSS([
        { p: 'padding', v: '10px' },
        { p: 'color', v: 'white' }
    ])
    //apply raw-string css in a UIList
    this.sideMenu.cssFromString('margin-top: 10px;')
    //loading an array of items to the UIList
    this.sideMenu.fromList(['Customers', 'Technical Users (support)']);
}
     * ```
     */
    abstract onViewDidLoad(): void;

    /**
     * Occurs when the View is being destroyed or removed from the DOM.
     * Use this to clean up resources, timers, or specific event listeners.
     */
    public onViewDidUnLoad(): void { }

    /**
     * (Optional overwrite) occurs when a Widget sends a message
     */
    public onWidgetMessage(message: WidgetMessage): void
    { }

    private view: UIView;
    protected shellPage: PageShell;
    private widgetContext: WidgetContext;
    private customPresenter?: ILayoutPresenter;
    protected buildedLayout: ViewLayout;

    /**
     * Initializes a new instance of the UIView.
     * @param customLayoutPresenter An optional presenter to handle custom rendering logic for the layout.
     */
    constructor(customLayoutPresenter?: ILayoutPresenter)
    {
        this.customPresenter = customLayoutPresenter;
    }

    /**
     * Request an instance of the Storage implementation 
     * for Session or Local storage by implementing IAppStorageProvider
     * * see:
     * * ```
     * interface IAppStorageProvider
     * ```
     * @param schemaName A unique id-name to determine the data scope
     */
    public requestLocalStorage(schemaName: string): AppStorage
    {
        if (this.disposed) return null
        return this.shellPage.requestStorage('local', schemaName);
    }

    /**
     * Request an instance of the Storage implementation for Session storage.
     * Useful for volatile data that should be cleared when the session ends.
     * @param schemaName A unique id-name to determine the data scope
     */
    public requestSessionStorage(schemaName: string): AppStorage
    {
        if (this.disposed) return null
        return this.shellPage.requestStorage('session', schemaName);
    }

    /**
     * Returns the current WidgetContext of this View, providing access to managed widgets and shell operations.
     */
    public viewContext(): WidgetContext
    {
        if (this.disposed) return null
        return this.widgetContext;
    }

    /**
     * Inflates a raw HTML string into a UITemplateView control within the context of this View.
     * @param rawHtml The HTML string to be transformed into a view component.
     */
    public inflateTemplateView(rawHtml: string): UITemplateView
    {
        if (this.disposed) return null
        return new UITemplateView(rawHtml, this.shellPage);
    }

    /**
     * Displays a standard modal dialog with defined title, text, and styling.
     * Automatically adapts between Bootstrap versions.
     * @param title The dialog header title.
     * @param text The body content of the dialog.
     * @param height The custom height (CSS value) for the modal.
     * @param modalClass Custom CSS classes to apply to the modal container.
     */
    public showDialog(title: string, text: string, height: string, modalClass: string): void
    {
        if (this.disposed) return
        UIDialog.$ = (PageShell.BOOTSTRAP_VERSION_NUMBER >= 5 ? new UIDialogBS5(this.shellPage, height, modalClass) : new UIDialog(this.shellPage))
            .setTitle(title)
            .setText(text)
            .action(new ModalAction({
                buttonText: 'Ok',
                dataDismiss: true
            }))
        UIDialog.$.show();
    }

    /**
     * Closes the currently active UIDialog instance if it exists.
     */
    public closeDialog()
    {
        if (this.disposed) return
        if (Misc.isNull(UIDialog.$)) return;
        UIDialog.$.closeDialog()
        UIDialog.$ = null
    }

    /**
     * Creates and returns a new UIDialog instance without showing it immediately.
     * @param params Configuration object containing title, modalHeight, and modalClass.
     */
    public createDialog({ title, modalHeight, modalClass }:
        {
            title: string;
            modalHeight?: string;
            modalClass?: string;
        }): UIDialog
    {
        if (this.disposed) return null
        if (PageShell.BOOTSTRAP_VERSION_NUMBER < 5)
            UIDialog.$ = new UIDialog(this.shellPage, '', modalHeight, modalClass).setTitle(title)
        else
            UIDialog.$ = new UIDialogBS5(this.shellPage, modalHeight, modalClass).setTitle(title)

        return UIDialog.$;
    }

    /**
     * Implementation of INotifiable. Handles internal notifications, 
     * such as triggering onViewDidLoad when the context is ready.
     * @param sender The object triggering the notification.
     * @param args Arguments passed along with the notification.
     */
    public onNotified(sender: any, args: any[]): void
    {
        if (this.disposed) return
        if (sender == 'FSWidgetContext')
            this.onViewDidLoad();
    }

    /**
     * The internal entry point for the UIView lifecycle. 
     * Orchestrates layout rendering, context creation, and widget binding.
     * @param mainShell The PageShell where this view will be rendered.
     * @param preventClear If true, prevents the shell from clearing existing content before rendering.
     */
    public initialize(mainShell: PageShell, preventClear: boolean = false)
    {
        UIPage.shell.loadBSVersion();

        this.shellPage = mainShell;

        this.buildedLayout = this.buildLayout();
        this.buildedLayout.render(mainShell, this.customPresenter, preventClear);

        var layoutCollection: string[] = this.buildedLayout.ElementsIdCollection();

        this.widgetContext = new WidgetContext(
            this.shellPage,
            layoutCollection,
            this.onWidgetMessage);

        this.view = this;
        this.view.composeView();
        this.widgetContext.build(this);
    }

    private disposed = false

    /**
     * Disposes of the View and its context, releasing memory and cleaning up managed widgets.
     */
    public dispose(): void
    {
        if (this.disposed) return
        try
        {
            this.onViewDidUnLoad();
        } catch { }

        this.widgetContext.clear()
        this.widgetContext = null
        this.disposed = true
    }

    /**
     * Get all Widgets attached and managed in this UIView
     */
    public managedWidgets(): Array<Widget>
    {
        if (this.disposed) return []
        if (this.widgetContext == null || this.widgetContext == undefined)
            return [];
        return this.widgetContext.getManagedWidgets();
    }

    /**
     * Adds one or more Widgets to a div specified in `ViewLayout`
     * @param layoutId An 'Id' of div contained in the `ViewLayout` class
     * @param widgets An array of Widget objects that will be bound to 'layoutId'
     */
    public addWidgets(layoutId: string, ...widgets: Widget[]): UIView
    {
        if (this.disposed) return null
        for (var i = 0; i < widgets.length; i++)
            this.widgetContext.addWidget(layoutId, widgets[i]);
        return this;
    }

    /**
     * Remove a Widget managed by this UIView
     */
    protected removeWidget(widget: Widget): void
    {
        if (this.disposed) return
        this.viewContext().removeWidget(widget);
    }

    /**
     * Finds a Widget managed by this UIView
     *
     * @param layoutId An 'Id' div contained in the `ViewLayout`class
     * @param widgetName The name of a Widget managed by this UIView and previously attached to the ViewLayout through the specified 'layoutId'
     */
    protected findWidget(layoutId: string, widgetName: string): Widget
    {
        if (this.disposed) return null
        return this.viewContext().findWidget(layoutId, widgetName);
    }

    /**
     * Create an alternative Widget Context that allows controlling 
     * a set of Widgets that are outside the main Div-app or that 
     * are in a different Div than the one used by the original 
     * Context of this UIView
     * @param managedDivIds The set of 'Id' divs managed by this Context Widget
     * @param messageProtocol A function that responds to the message triggered by this context indicating its complete loading
     */
    protected createWidgetContext(managedDivIds: string[], messageProtocol?: Function): WidgetContext
    {
        if (this.disposed) return null
        if (null == this.shellPage || undefined == this.shellPage)
            throw 'FSView.createWidgetContext(): It is not possible to do this as the View is not yet initialized. If you are making this call inside the constructor(), move it inside the composeView() function.';

        return new WidgetContext(
            this.shellPage,
            managedDivIds,
            messageProtocol
        );
    }
}